// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetHealthData, GetHealthResponses, GetApiData, GetApiResponses, GetApiOrganizationsData, GetApiOrganizationsResponses, PostApiOrganizationsData, PostApiOrganizationsResponses, GetApiOrganizationsByIdData, GetApiOrganizationsByIdResponses, GetApiOrganizationsByIdProgramsData, GetApiOrganizationsByIdProgramsResponses, GetApiOrganizationsSubdomainBySubdomainData, GetApiOrganizationsSubdomainBySubdomainResponses, GetApiOrganizationsBySubdomainProgramsByProgramIdData, GetApiOrganizationsBySubdomainProgramsByProgramIdResponses, GetApiProgramsData, GetApiProgramsResponses, PostApiProgramsData, PostApiProgramsResponses, DeleteApiProgramsByIdData, DeleteApiProgramsByIdResponses, GetApiProgramsByIdData, GetApiProgramsByIdResponses, PatchApiProgramsByIdData, PatchApiProgramsByIdResponses, GetApiEnrollmentsData, GetApiEnrollmentsResponses, PostApiEnrollmentsData, PostApiEnrollmentsResponses, GetApiEnrollmentsByIdData, GetApiEnrollmentsByIdResponses, GetApiEnrollmentsInvoiceByInvoiceHandleData, GetApiEnrollmentsInvoiceByInvoiceHandleResponses, GetApiUserEnrollmentsData, GetApiUserEnrollmentsResponses, GetApiUserMembersData, GetApiUserMembersResponses, PostApiUserMembersData, PostApiUserMembersResponses, PatchApiUserMembersByIdData, PatchApiUserMembersByIdResponses, PostApiPaymentsSessionChargeData, PostApiPaymentsSessionChargeResponses, GetApiPaymentsByHandleStatusData, GetApiPaymentsByHandleStatusResponses, PostApiWebhooksFrisbiiData, PostApiWebhooksFrisbiiResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

export const getApi = <ThrowOnError extends boolean = false>(options?: Options<GetApiData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiResponses, unknown, ThrowOnError>({
        url: '/api',
        ...options
    });
};

export const getApiOrganizations = <ThrowOnError extends boolean = false>(options?: Options<GetApiOrganizationsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiOrganizationsResponses, unknown, ThrowOnError>({
        url: '/api/organizations',
        ...options
    });
};

export const postApiOrganizations = <ThrowOnError extends boolean = false>(options?: Options<PostApiOrganizationsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiOrganizationsResponses, unknown, ThrowOnError>({
        url: '/api/organizations',
        ...options
    });
};

export const getApiOrganizationsById = <ThrowOnError extends boolean = false>(options?: Options<GetApiOrganizationsByIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiOrganizationsByIdResponses, unknown, ThrowOnError>({
        url: '/api/organizations/{id}',
        ...options
    });
};

export const getApiOrganizationsByIdPrograms = <ThrowOnError extends boolean = false>(options?: Options<GetApiOrganizationsByIdProgramsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiOrganizationsByIdProgramsResponses, unknown, ThrowOnError>({
        url: '/api/organizations/{id}/programs',
        ...options
    });
};

export const getApiOrganizationsSubdomainBySubdomain = <ThrowOnError extends boolean = false>(options?: Options<GetApiOrganizationsSubdomainBySubdomainData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiOrganizationsSubdomainBySubdomainResponses, unknown, ThrowOnError>({
        url: '/api/organizations/subdomain/{subdomain}',
        ...options
    });
};

export const getApiOrganizationsBySubdomainProgramsByProgramId = <ThrowOnError extends boolean = false>(options?: Options<GetApiOrganizationsBySubdomainProgramsByProgramIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiOrganizationsBySubdomainProgramsByProgramIdResponses, unknown, ThrowOnError>({
        url: '/api/organizations/{subdomain}/programs/{programId}',
        ...options
    });
};

export const getApiPrograms = <ThrowOnError extends boolean = false>(options?: Options<GetApiProgramsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiProgramsResponses, unknown, ThrowOnError>({
        url: '/api/programs',
        ...options
    });
};

export const postApiPrograms = <ThrowOnError extends boolean = false>(options?: Options<PostApiProgramsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiProgramsResponses, unknown, ThrowOnError>({
        url: '/api/programs',
        ...options
    });
};

export const deleteApiProgramsById = <ThrowOnError extends boolean = false>(options?: Options<DeleteApiProgramsByIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<DeleteApiProgramsByIdResponses, unknown, ThrowOnError>({
        url: '/api/programs/{id}',
        ...options
    });
};

export const getApiProgramsById = <ThrowOnError extends boolean = false>(options?: Options<GetApiProgramsByIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiProgramsByIdResponses, unknown, ThrowOnError>({
        url: '/api/programs/{id}',
        ...options
    });
};

export const patchApiProgramsById = <ThrowOnError extends boolean = false>(options?: Options<PatchApiProgramsByIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).patch<PatchApiProgramsByIdResponses, unknown, ThrowOnError>({
        url: '/api/programs/{id}',
        ...options
    });
};

export const getApiEnrollments = <ThrowOnError extends boolean = false>(options?: Options<GetApiEnrollmentsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiEnrollmentsResponses, unknown, ThrowOnError>({
        url: '/api/enrollments',
        ...options
    });
};

export const postApiEnrollments = <ThrowOnError extends boolean = false>(options?: Options<PostApiEnrollmentsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiEnrollmentsResponses, unknown, ThrowOnError>({
        url: '/api/enrollments',
        ...options
    });
};

export const getApiEnrollmentsById = <ThrowOnError extends boolean = false>(options?: Options<GetApiEnrollmentsByIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiEnrollmentsByIdResponses, unknown, ThrowOnError>({
        url: '/api/enrollments/{id}',
        ...options
    });
};

export const getApiEnrollmentsInvoiceByInvoiceHandle = <ThrowOnError extends boolean = false>(options?: Options<GetApiEnrollmentsInvoiceByInvoiceHandleData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiEnrollmentsInvoiceByInvoiceHandleResponses, unknown, ThrowOnError>({
        url: '/api/enrollments/invoice/{invoiceHandle}',
        ...options
    });
};

export const getApiUserEnrollments = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserEnrollmentsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiUserEnrollmentsResponses, unknown, ThrowOnError>({
        url: '/api/user/enrollments',
        ...options
    });
};

export const getApiUserMembers = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserMembersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiUserMembersResponses, unknown, ThrowOnError>({
        url: '/api/user/members',
        ...options
    });
};

export const postApiUserMembers = <ThrowOnError extends boolean = false>(options?: Options<PostApiUserMembersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiUserMembersResponses, unknown, ThrowOnError>({
        url: '/api/user/members',
        ...options
    });
};

export const patchApiUserMembersById = <ThrowOnError extends boolean = false>(options?: Options<PatchApiUserMembersByIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).patch<PatchApiUserMembersByIdResponses, unknown, ThrowOnError>({
        url: '/api/user/members/{id}',
        ...options
    });
};

export const postApiPaymentsSessionCharge = <ThrowOnError extends boolean = false>(options?: Options<PostApiPaymentsSessionChargeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiPaymentsSessionChargeResponses, unknown, ThrowOnError>({
        url: '/api/payments/session/charge',
        ...options
    });
};

export const getApiPaymentsByHandleStatus = <ThrowOnError extends boolean = false>(options?: Options<GetApiPaymentsByHandleStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiPaymentsByHandleStatusResponses, unknown, ThrowOnError>({
        url: '/api/payments/{handle}/status',
        ...options
    });
};

export const postApiWebhooksFrisbii = <ThrowOnError extends boolean = false>(options?: Options<PostApiWebhooksFrisbiiData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiWebhooksFrisbiiResponses, unknown, ThrowOnError>({
        url: '/api/webhooks/frisbii',
        ...options
    });
};