// This file is auto-generated by @hey-api/openapi-ts

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type GetApiResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations';
};

export type GetApiOrganizationsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations';
};

export type PostApiOrganizationsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiOrganizationsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations/{id}';
};

export type GetApiOrganizationsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiOrganizationsByIdProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations/{id}/programs';
};

export type GetApiOrganizationsByIdProgramsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiOrganizationsSubdomainBySubdomainData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations/subdomain/{subdomain}';
};

export type GetApiOrganizationsSubdomainBySubdomainResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiOrganizationsBySubdomainProgramsByProgramIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations/{subdomain}/programs/{programId}';
};

export type GetApiOrganizationsBySubdomainProgramsByProgramIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/programs';
};

export type GetApiProgramsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/programs';
};

export type PostApiProgramsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiProgramsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/programs/{id}';
};

export type DeleteApiProgramsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiProgramsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/programs/{id}';
};

export type GetApiProgramsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchApiProgramsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/programs/{id}';
};

export type PatchApiProgramsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiEnrollmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enrollments';
};

export type GetApiEnrollmentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiEnrollmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enrollments';
};

export type PostApiEnrollmentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiEnrollmentsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enrollments/{id}';
};

export type GetApiEnrollmentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiEnrollmentsInvoiceByInvoiceHandleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enrollments/invoice/{invoiceHandle}';
};

export type GetApiEnrollmentsInvoiceByInvoiceHandleResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserEnrollmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/enrollments';
};

export type GetApiUserEnrollmentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/members';
};

export type GetApiUserMembersResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiUserMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/members';
};

export type PostApiUserMembersResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchApiUserMembersByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/members/{id}';
};

export type PatchApiUserMembersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiPaymentsSessionChargeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/session/charge';
};

export type PostApiPaymentsSessionChargeResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiPaymentsByHandleStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/{handle}/status';
};

export type GetApiPaymentsByHandleStatusResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiWebhooksFrisbiiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/webhooks/frisbii';
};

export type PostApiWebhooksFrisbiiResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};