// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getHealth, getApi, getApiOrganizations, postApiOrganizations, getApiOrganizationsById, getApiOrganizationsByIdPrograms, getApiOrganizationsSubdomainBySubdomain, getApiOrganizationsBySubdomainProgramsByProgramId, getApiPrograms, postApiPrograms, deleteApiProgramsById, getApiProgramsById, patchApiProgramsById, getApiEnrollments, postApiEnrollments, getApiEnrollmentsById, getApiEnrollmentsInvoiceByInvoiceHandle, getApiUserEnrollments, getApiUserMembers, postApiUserMembers, patchApiUserMembersById, postApiPaymentsSessionCharge, getApiPaymentsByHandleStatus, postApiWebhooksFrisbii } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { GetHealthData, GetApiData, GetApiOrganizationsData, PostApiOrganizationsData, GetApiOrganizationsByIdData, GetApiOrganizationsByIdProgramsData, GetApiOrganizationsSubdomainBySubdomainData, GetApiOrganizationsBySubdomainProgramsByProgramIdData, GetApiProgramsData, PostApiProgramsData, DeleteApiProgramsByIdData, GetApiProgramsByIdData, PatchApiProgramsByIdData, GetApiEnrollmentsData, PostApiEnrollmentsData, GetApiEnrollmentsByIdData, GetApiEnrollmentsInvoiceByInvoiceHandleData, GetApiUserEnrollmentsData, GetApiUserMembersData, PostApiUserMembersData, PatchApiUserMembersByIdData, PostApiPaymentsSessionChargeData, GetApiPaymentsByHandleStatusData, PostApiWebhooksFrisbiiData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getHealth({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getHealthQueryKey(options)
    });
};

export const getApiQueryKey = (options?: Options<GetApiData>) => createQueryKey('getApi', options);

export const getApiOptions = (options?: Options<GetApiData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApi({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiQueryKey(options)
    });
};

export const getApiOrganizationsQueryKey = (options?: Options<GetApiOrganizationsData>) => createQueryKey('getApiOrganizations', options);

export const getApiOrganizationsOptions = (options?: Options<GetApiOrganizationsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizations({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsQueryKey(options)
    });
};

export const postApiOrganizationsMutation = (options?: Partial<Options<PostApiOrganizationsData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiOrganizationsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiOrganizationsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiOrganizations({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiOrganizationsByIdQueryKey = (options?: Options<GetApiOrganizationsByIdData>) => createQueryKey('getApiOrganizationsById', options);

export const getApiOrganizationsByIdOptions = (options?: Options<GetApiOrganizationsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsByIdQueryKey(options)
    });
};

export const getApiOrganizationsByIdProgramsQueryKey = (options?: Options<GetApiOrganizationsByIdProgramsData>) => createQueryKey('getApiOrganizationsByIdPrograms', options);

export const getApiOrganizationsByIdProgramsOptions = (options?: Options<GetApiOrganizationsByIdProgramsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsByIdPrograms({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsByIdProgramsQueryKey(options)
    });
};

export const getApiOrganizationsSubdomainBySubdomainQueryKey = (options?: Options<GetApiOrganizationsSubdomainBySubdomainData>) => createQueryKey('getApiOrganizationsSubdomainBySubdomain', options);

export const getApiOrganizationsSubdomainBySubdomainOptions = (options?: Options<GetApiOrganizationsSubdomainBySubdomainData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsSubdomainBySubdomain({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsSubdomainBySubdomainQueryKey(options)
    });
};

export const getApiOrganizationsBySubdomainProgramsByProgramIdQueryKey = (options?: Options<GetApiOrganizationsBySubdomainProgramsByProgramIdData>) => createQueryKey('getApiOrganizationsBySubdomainProgramsByProgramId', options);

export const getApiOrganizationsBySubdomainProgramsByProgramIdOptions = (options?: Options<GetApiOrganizationsBySubdomainProgramsByProgramIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsBySubdomainProgramsByProgramId({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsBySubdomainProgramsByProgramIdQueryKey(options)
    });
};

export const getApiProgramsQueryKey = (options?: Options<GetApiProgramsData>) => createQueryKey('getApiPrograms', options);

export const getApiProgramsOptions = (options?: Options<GetApiProgramsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiPrograms({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiProgramsQueryKey(options)
    });
};

export const postApiProgramsMutation = (options?: Partial<Options<PostApiProgramsData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiProgramsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiProgramsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPrograms({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiProgramsByIdMutation = (options?: Partial<Options<DeleteApiProgramsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiProgramsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiProgramsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiProgramsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiProgramsByIdQueryKey = (options?: Options<GetApiProgramsByIdData>) => createQueryKey('getApiProgramsById', options);

export const getApiProgramsByIdOptions = (options?: Options<GetApiProgramsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiProgramsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiProgramsByIdQueryKey(options)
    });
};

export const patchApiProgramsByIdMutation = (options?: Partial<Options<PatchApiProgramsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PatchApiProgramsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiProgramsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiProgramsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiEnrollmentsQueryKey = (options?: Options<GetApiEnrollmentsData>) => createQueryKey('getApiEnrollments', options);

export const getApiEnrollmentsOptions = (options?: Options<GetApiEnrollmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiEnrollments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiEnrollmentsQueryKey(options)
    });
};

export const postApiEnrollmentsMutation = (options?: Partial<Options<PostApiEnrollmentsData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiEnrollmentsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiEnrollmentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiEnrollments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiEnrollmentsByIdQueryKey = (options?: Options<GetApiEnrollmentsByIdData>) => createQueryKey('getApiEnrollmentsById', options);

export const getApiEnrollmentsByIdOptions = (options?: Options<GetApiEnrollmentsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiEnrollmentsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiEnrollmentsByIdQueryKey(options)
    });
};

export const getApiEnrollmentsInvoiceByInvoiceHandleQueryKey = (options?: Options<GetApiEnrollmentsInvoiceByInvoiceHandleData>) => createQueryKey('getApiEnrollmentsInvoiceByInvoiceHandle', options);

export const getApiEnrollmentsInvoiceByInvoiceHandleOptions = (options?: Options<GetApiEnrollmentsInvoiceByInvoiceHandleData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiEnrollmentsInvoiceByInvoiceHandle({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiEnrollmentsInvoiceByInvoiceHandleQueryKey(options)
    });
};

export const getApiUserEnrollmentsQueryKey = (options?: Options<GetApiUserEnrollmentsData>) => createQueryKey('getApiUserEnrollments', options);

export const getApiUserEnrollmentsOptions = (options?: Options<GetApiUserEnrollmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiUserEnrollments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUserEnrollmentsQueryKey(options)
    });
};

export const getApiUserMembersQueryKey = (options?: Options<GetApiUserMembersData>) => createQueryKey('getApiUserMembers', options);

export const getApiUserMembersOptions = (options?: Options<GetApiUserMembersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiUserMembers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUserMembersQueryKey(options)
    });
};

export const postApiUserMembersMutation = (options?: Partial<Options<PostApiUserMembersData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiUserMembersData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiUserMembersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiUserMembers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const patchApiUserMembersByIdMutation = (options?: Partial<Options<PatchApiUserMembersByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PatchApiUserMembersByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiUserMembersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiUserMembersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiPaymentsSessionChargeMutation = (options?: Partial<Options<PostApiPaymentsSessionChargeData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiPaymentsSessionChargeData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiPaymentsSessionChargeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPaymentsSessionCharge({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiPaymentsByHandleStatusQueryKey = (options?: Options<GetApiPaymentsByHandleStatusData>) => createQueryKey('getApiPaymentsByHandleStatus', options);

export const getApiPaymentsByHandleStatusOptions = (options?: Options<GetApiPaymentsByHandleStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiPaymentsByHandleStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiPaymentsByHandleStatusQueryKey(options)
    });
};

export const postApiWebhooksFrisbiiMutation = (options?: Partial<Options<PostApiWebhooksFrisbiiData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiWebhooksFrisbiiData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiWebhooksFrisbiiData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiWebhooksFrisbii({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};