// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getHealth, getApi, getApiOrganizations, postApiOrganizations, getApiOrganizationsById, getApiOrganizationsByIdPrograms, getApiOrganizationsSubdomainBySubdomain, getApiOrganizationsBySubdomainProgramsByProgramId, getApiPrograms, postApiPrograms, deleteApiProgramsById, getApiProgramsById, patchApiProgramsById, getApiEnrollments, postApiEnrollments, getApiEnrollmentsById, getApiEnrollmentsInvoiceByInvoiceHandle, postApiPaymentsSessionCharge, getApiPaymentsHandleStatus, getApiUserEnrollments, getApiUserMembers, postApiUserMembers, patchApiUserMembersById, postApiWebhooksFrisbiiOrgSlug } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { GetHealthData, GetApiData, GetApiOrganizationsData, PostApiOrganizationsData, PostApiOrganizationsError, PostApiOrganizationsResponse, GetApiOrganizationsByIdData, GetApiOrganizationsByIdProgramsData, GetApiOrganizationsSubdomainBySubdomainData, GetApiOrganizationsBySubdomainProgramsByProgramIdData, GetApiProgramsData, PostApiProgramsData, PostApiProgramsError, PostApiProgramsResponse, DeleteApiProgramsByIdData, DeleteApiProgramsByIdError, DeleteApiProgramsByIdResponse, GetApiProgramsByIdData, PatchApiProgramsByIdData, PatchApiProgramsByIdError, PatchApiProgramsByIdResponse, GetApiEnrollmentsData, PostApiEnrollmentsData, PostApiEnrollmentsError, PostApiEnrollmentsResponse, GetApiEnrollmentsByIdData, GetApiEnrollmentsInvoiceByInvoiceHandleData, PostApiPaymentsSessionChargeData, PostApiPaymentsSessionChargeError, PostApiPaymentsSessionChargeResponse, GetApiPaymentsHandleStatusData, GetApiUserEnrollmentsData, GetApiUserMembersData, PostApiUserMembersData, PostApiUserMembersError, PostApiUserMembersResponse, PatchApiUserMembersByIdData, PatchApiUserMembersByIdError, PatchApiUserMembersByIdResponse, PostApiWebhooksFrisbiiOrgSlugData, PostApiWebhooksFrisbiiOrgSlugError, PostApiWebhooksFrisbiiOrgSlugResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getHealth({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getHealthQueryKey(options)
    });
};

export const getApiQueryKey = (options?: Options<GetApiData>) => createQueryKey('getApi', options);

export const getApiOptions = (options?: Options<GetApiData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApi({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiQueryKey(options)
    });
};

export const getApiOrganizationsQueryKey = (options?: Options<GetApiOrganizationsData>) => createQueryKey('getApiOrganizations', options);

/**
 * List organizations
 * Get all organizations
 */
export const getApiOrganizationsOptions = (options?: Options<GetApiOrganizationsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizations({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsQueryKey(options)
    });
};

/**
 * Create organization
 * Create a new organization
 */
export const postApiOrganizationsMutation = (options?: Partial<Options<PostApiOrganizationsData>>): UseMutationOptions<PostApiOrganizationsResponse, PostApiOrganizationsError, Options<PostApiOrganizationsData>> => {
    const mutationOptions: UseMutationOptions<PostApiOrganizationsResponse, PostApiOrganizationsError, Options<PostApiOrganizationsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiOrganizations({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiOrganizationsByIdQueryKey = (options: Options<GetApiOrganizationsByIdData>) => createQueryKey('getApiOrganizationsById', options);

/**
 * Get organization
 * Get a specific organization by ID
 */
export const getApiOrganizationsByIdOptions = (options: Options<GetApiOrganizationsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsByIdQueryKey(options)
    });
};

export const getApiOrganizationsByIdProgramsQueryKey = (options: Options<GetApiOrganizationsByIdProgramsData>) => createQueryKey('getApiOrganizationsByIdPrograms', options);

/**
 * Get organization with programs
 * Get an organization with all its programs
 */
export const getApiOrganizationsByIdProgramsOptions = (options: Options<GetApiOrganizationsByIdProgramsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsByIdPrograms({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsByIdProgramsQueryKey(options)
    });
};

export const getApiOrganizationsSubdomainBySubdomainQueryKey = (options: Options<GetApiOrganizationsSubdomainBySubdomainData>) => createQueryKey('getApiOrganizationsSubdomainBySubdomain', options);

/**
 * Get organization by subdomain
 * Get an organization by its subdomain with programs and enrollment counts
 */
export const getApiOrganizationsSubdomainBySubdomainOptions = (options: Options<GetApiOrganizationsSubdomainBySubdomainData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsSubdomainBySubdomain({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsSubdomainBySubdomainQueryKey(options)
    });
};

export const getApiOrganizationsBySubdomainProgramsByProgramIdQueryKey = (options: Options<GetApiOrganizationsBySubdomainProgramsByProgramIdData>) => createQueryKey('getApiOrganizationsBySubdomainProgramsByProgramId', options);

/**
 * Get specific program from organization
 * Get a specific program that belongs to an organization by subdomain
 */
export const getApiOrganizationsBySubdomainProgramsByProgramIdOptions = (options: Options<GetApiOrganizationsBySubdomainProgramsByProgramIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiOrganizationsBySubdomainProgramsByProgramId({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiOrganizationsBySubdomainProgramsByProgramIdQueryKey(options)
    });
};

export const getApiProgramsQueryKey = (options?: Options<GetApiProgramsData>) => createQueryKey('getApiPrograms', options);

/**
 * List programs
 * Get all programs
 */
export const getApiProgramsOptions = (options?: Options<GetApiProgramsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiPrograms({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiProgramsQueryKey(options)
    });
};

/**
 * Create program
 * Create a new program
 */
export const postApiProgramsMutation = (options?: Partial<Options<PostApiProgramsData>>): UseMutationOptions<PostApiProgramsResponse, PostApiProgramsError, Options<PostApiProgramsData>> => {
    const mutationOptions: UseMutationOptions<PostApiProgramsResponse, PostApiProgramsError, Options<PostApiProgramsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPrograms({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete program
 * Delete a program by ID
 */
export const deleteApiProgramsByIdMutation = (options?: Partial<Options<DeleteApiProgramsByIdData>>): UseMutationOptions<DeleteApiProgramsByIdResponse, DeleteApiProgramsByIdError, Options<DeleteApiProgramsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiProgramsByIdResponse, DeleteApiProgramsByIdError, Options<DeleteApiProgramsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiProgramsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiProgramsByIdQueryKey = (options: Options<GetApiProgramsByIdData>) => createQueryKey('getApiProgramsById', options);

/**
 * Get program
 * Get a specific program by ID
 */
export const getApiProgramsByIdOptions = (options: Options<GetApiProgramsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiProgramsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiProgramsByIdQueryKey(options)
    });
};

/**
 * Update program
 * Update an existing program
 */
export const patchApiProgramsByIdMutation = (options?: Partial<Options<PatchApiProgramsByIdData>>): UseMutationOptions<PatchApiProgramsByIdResponse, PatchApiProgramsByIdError, Options<PatchApiProgramsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchApiProgramsByIdResponse, PatchApiProgramsByIdError, Options<PatchApiProgramsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiProgramsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiEnrollmentsQueryKey = (options?: Options<GetApiEnrollmentsData>) => createQueryKey('getApiEnrollments', options);

/**
 * List enrollments
 * Get all program enrollments
 */
export const getApiEnrollmentsOptions = (options?: Options<GetApiEnrollmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiEnrollments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiEnrollmentsQueryKey(options)
    });
};

/**
 * Create enrollment
 * Enroll a member in a program
 */
export const postApiEnrollmentsMutation = (options?: Partial<Options<PostApiEnrollmentsData>>): UseMutationOptions<PostApiEnrollmentsResponse, PostApiEnrollmentsError, Options<PostApiEnrollmentsData>> => {
    const mutationOptions: UseMutationOptions<PostApiEnrollmentsResponse, PostApiEnrollmentsError, Options<PostApiEnrollmentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiEnrollments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiEnrollmentsByIdQueryKey = (options: Options<GetApiEnrollmentsByIdData>) => createQueryKey('getApiEnrollmentsById', options);

/**
 * Get enrollment
 * Get a specific enrollment by ID
 */
export const getApiEnrollmentsByIdOptions = (options: Options<GetApiEnrollmentsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiEnrollmentsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiEnrollmentsByIdQueryKey(options)
    });
};

export const getApiEnrollmentsInvoiceByInvoiceHandleQueryKey = (options: Options<GetApiEnrollmentsInvoiceByInvoiceHandleData>) => createQueryKey('getApiEnrollmentsInvoiceByInvoiceHandle', options);

/**
 * Get enrollment by invoice handle
 * Get a specific enrollment by its invoice handle
 */
export const getApiEnrollmentsInvoiceByInvoiceHandleOptions = (options: Options<GetApiEnrollmentsInvoiceByInvoiceHandleData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiEnrollmentsInvoiceByInvoiceHandle({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiEnrollmentsInvoiceByInvoiceHandleQueryKey(options)
    });
};

export const postApiPaymentsSessionChargeMutation = (options?: Partial<Options<PostApiPaymentsSessionChargeData>>): UseMutationOptions<PostApiPaymentsSessionChargeResponse, PostApiPaymentsSessionChargeError, Options<PostApiPaymentsSessionChargeData>> => {
    const mutationOptions: UseMutationOptions<PostApiPaymentsSessionChargeResponse, PostApiPaymentsSessionChargeError, Options<PostApiPaymentsSessionChargeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPaymentsSessionCharge({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiPaymentsHandleStatusQueryKey = (options: Options<GetApiPaymentsHandleStatusData>) => createQueryKey('getApiPaymentsHandleStatus', options);

export const getApiPaymentsHandleStatusOptions = (options: Options<GetApiPaymentsHandleStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiPaymentsHandleStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiPaymentsHandleStatusQueryKey(options)
    });
};

export const getApiUserEnrollmentsQueryKey = (options?: Options<GetApiUserEnrollmentsData>) => createQueryKey('getApiUserEnrollments', options);

/**
 * List my enrollments
 * List all enrollments for the authenticated user's member records
 */
export const getApiUserEnrollmentsOptions = (options?: Options<GetApiUserEnrollmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiUserEnrollments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUserEnrollmentsQueryKey(options)
    });
};

export const getApiUserMembersQueryKey = (options?: Options<GetApiUserMembersData>) => createQueryKey('getApiUserMembers', options);

/**
 * List my member records
 * Get all member records for the authenticated user
 */
export const getApiUserMembersOptions = (options?: Options<GetApiUserMembersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getApiUserMembers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiUserMembersQueryKey(options)
    });
};

/**
 * Create my member record
 * Create a new member record for the authenticated user
 */
export const postApiUserMembersMutation = (options?: Partial<Options<PostApiUserMembersData>>): UseMutationOptions<PostApiUserMembersResponse, PostApiUserMembersError, Options<PostApiUserMembersData>> => {
    const mutationOptions: UseMutationOptions<PostApiUserMembersResponse, PostApiUserMembersError, Options<PostApiUserMembersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiUserMembers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update my member record
 * Partially update a member record owned by the authenticated user
 */
export const patchApiUserMembersByIdMutation = (options?: Partial<Options<PatchApiUserMembersByIdData>>): UseMutationOptions<PatchApiUserMembersByIdResponse, PatchApiUserMembersByIdError, Options<PatchApiUserMembersByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchApiUserMembersByIdResponse, PatchApiUserMembersByIdError, Options<PatchApiUserMembersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiUserMembersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiWebhooksFrisbiiOrgSlugMutation = (options?: Partial<Options<PostApiWebhooksFrisbiiOrgSlugData>>): UseMutationOptions<PostApiWebhooksFrisbiiOrgSlugResponse, PostApiWebhooksFrisbiiOrgSlugError, Options<PostApiWebhooksFrisbiiOrgSlugData>> => {
    const mutationOptions: UseMutationOptions<PostApiWebhooksFrisbiiOrgSlugResponse, PostApiWebhooksFrisbiiOrgSlugError, Options<PostApiWebhooksFrisbiiOrgSlugData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiWebhooksFrisbiiOrgSlug({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};